# Generated by Django 5.2.6 on 2025-09-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('estimated_duration', models.IntegerField()),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_long', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_long', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('driving_time', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('fuel_amount', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='trips.trip')),
            ],
        ),
    ]
