# Generated by Django 5.2.6 on 2025-09-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eld', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='logsheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_driving_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_on_duty_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_off_duty_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_sleeper_berth_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsheets', to='eld.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsheets', to='trips.trip')),
            ],
        ),
    ]
