# Generated by Django 5.2.6 on 2025-09-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('current_cycle_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HOSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duty_status', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_logs', to='eld.driver')),
            ],
        ),
    ]
